// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx3dmYZWEnzm79KVR2CdLDacHc9o3JAZE',
    appId: '1:533127468146:web:d4df3065aa345ce1865eeb',
    messagingSenderId: '533127468146',
    projectId: 'flutter-firebase-52255',
    authDomain: 'flutter-firebase-52255.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-52255-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-52255.appspot.com',
    measurementId: 'G-RB1FSCNMM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwY6jon40mhOSgvCDJnYohaP7CIX4BTPg',
    appId: '1:533127468146:android:52fdc2d2b3faa7c9865eeb',
    messagingSenderId: '533127468146',
    projectId: 'flutter-firebase-52255',
    databaseURL: 'https://flutter-firebase-52255-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-52255.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4lJWQJDtohCEe5gmLUw-kNh2qMuMOmWg',
    appId: '1:533127468146:ios:e5879d5db1308633865eeb',
    messagingSenderId: '533127468146',
    projectId: 'flutter-firebase-52255',
    databaseURL: 'https://flutter-firebase-52255-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-52255.appspot.com',
    androidClientId: '533127468146-i7vtpk81g4tki6p6obrsmhtp843trep5.apps.googleusercontent.com',
    iosClientId: '533127468146-ghioajqlg3u4rqqfihmq3uk8lt128hgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4lJWQJDtohCEe5gmLUw-kNh2qMuMOmWg',
    appId: '1:533127468146:ios:e5879d5db1308633865eeb',
    messagingSenderId: '533127468146',
    projectId: 'flutter-firebase-52255',
    databaseURL: 'https://flutter-firebase-52255-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-52255.appspot.com',
    androidClientId: '533127468146-i7vtpk81g4tki6p6obrsmhtp843trep5.apps.googleusercontent.com',
    iosClientId: '533127468146-ghioajqlg3u4rqqfihmq3uk8lt128hgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
